name: absherthone
description: "A new Flutter project."
publish_to: "none"
version: 0.2.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
    
  #In here we will import the packages that we will use in our project.  
  #Used to show a splash screen in the start of app.
  flutter_native_splash: ^2.4.4
  #Provides a responsivness
  flutter_screenutil: ^5.9.3
  #For future plan to add both english and arabic language.
  flutter_localization: ^0.3.1
  #Svg images.
  flutter_svg: ^2.0.17
  #Onboarding screen.
  animated_introduction: ^1.0.4
  #Lottie Animation.
  lottie: ^3.3.1
  #Animations.
  animate_do: ^3.3.7
  #Speech to text.
  speech_to_text: ^7.0.0
  #icons
  iconsax: ^0.0.8
  #Drawer menu 
  hidden_drawer_menu: ^3.0.1
  #upper dialog.
  fluttertoast: ^8.2.12
  pin_code_fields: ^8.0.1

  shorebird_code_push: ^2.0.3


  

  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  supabase_flutter: ^2.8.3
  fpdart: ^1.1.1
  app_links: ^3.1.0
  flutter_bloc: ^9.0.0
  get_it: ^8.0.3
  intl: ^0.19.0
  flutter_datetime_picker: ^1.5.1
  build_runner: ^2.4.15
  flutter_spinkit: ^5.2.1
  equatable: ^2.0.7
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  bloc: ^9.0.0
  flutter_gen: ^5.10.0
  record: ^6.0.0
  flutter_sound: ^9.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


  
  
flutter:
  generate: true
  
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/

  fonts:
    #Arabic font when needed.
    - family: IBMPlexSansArabic
      fonts:
        - asset: assets/fonts/arabic/IBMPlexSansArabic-Regular.ttf
        - asset: assets/fonts/arabic/IBMPlexSansArabic-Bold.ttf
          weight: 700
    #English font "Main font".
    - family: Share
      fonts:
        - asset: assets/fonts/english/Share-Regular.ttf   
        

flutter_native_splash:
  android: true
  ios: true
  web: false
  fullscreen: true
  background_image: assets/images/splash.png




