// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVrVN1NLiaLe_VhYaHSR9JdXsxeKNslJ0',
    appId: '1:637375575735:android:781201cc7aa58ee60e3f32',
    messagingSenderId: '637375575735',
    projectId: 'absher-10be2',
    storageBucket: 'absher-10be2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8SdMejnAdrRYNqLYRjnI_w6-1Y2hcQ9E',
    appId: '1:637375575735:ios:bc14ccdfd698eec20e3f32',
    messagingSenderId: '637375575735',
    projectId: 'absher-10be2',
    storageBucket: 'absher-10be2.firebasestorage.app',
    iosBundleId: 'com.example.absherthone',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC22VoQCuBkR7oEDckQ3mugdIGfl2Fhd3c',
    appId: '1:637375575735:web:2ae1eb1f6b59e0550e3f32',
    messagingSenderId: '637375575735',
    projectId: 'absher-10be2',
    authDomain: 'absher-10be2.firebaseapp.com',
    storageBucket: 'absher-10be2.firebasestorage.app',
    measurementId: 'G-28QTVMJLTC',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8SdMejnAdrRYNqLYRjnI_w6-1Y2hcQ9E',
    appId: '1:637375575735:ios:bc14ccdfd698eec20e3f32',
    messagingSenderId: '637375575735',
    projectId: 'absher-10be2',
    storageBucket: 'absher-10be2.firebasestorage.app',
    iosBundleId: 'com.example.absherthone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC22VoQCuBkR7oEDckQ3mugdIGfl2Fhd3c',
    appId: '1:637375575735:web:cc8521441e48f0e20e3f32',
    messagingSenderId: '637375575735',
    projectId: 'absher-10be2',
    authDomain: 'absher-10be2.firebaseapp.com',
    storageBucket: 'absher-10be2.firebasestorage.app',
    measurementId: 'G-NG2E6HN6QX',
  );

}